name: S.Net Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cloudflared on Runner
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_command: /usr/local/bin/cloudflared access ssh --hostname %h
          script: |
            # Sesuai dengan hasil 'dir' kamu tadi
            cd ~/dev/serverdev 
            
            git pull origin main
            
            # Install & Generate Prisma (Karena ada folder prisma di dir kamu)
            /home/fathur/.bun/bin/bun install
            /home/fathur/.bun/bin/bunx prisma generate
            
            # Restart service
            sudo systemctl restart server-net